### ISSUE TITLE
K8s Resource Management: autoscaling

### ISSUE THREAD

**Issue by kevinintel** [opea-project/GenAIInfra#144] opened 2024-07-01 08:28 UTC

**Comment by jfding** [comment] 2024-07-18 01:58
The resource management of Kubernetes for OPEA workloads is a very big problem, we need to break down to a few specific requirements in the future, according to the feedbacks from developer and landing customers. This issue can be a placeholder currently, to collect all related feedbacks.

**Comment by jfding** [comment] 2024-07-18 02:59
+ Malini as well to work on this ticket.

**Comment by daisy-ycguo** [comment] 2024-07-25 03:54
I don't think it is a valid issue.
@kevinintel @jfding @mkbhanda what's your option ? how to handle it?

**Comment by mkbhanda** [comment] 2024-07-25 05:16
Let us make this a feature request, a longer-term endeavor. It is not a bug. Also OK to close it for now if @jfding agrees.

**Comment by endomorphosis** [comment] 2024-07-31 04:26
the term "resource management" is too vague for me to provide any meaningful input beyond the changes to the manifests so that multiple containers of the same service are not staged on the same machine.

**Comment by kevinintel** [comment] 2024-07-31 04:28
It’s a feature of roadmap.

**Comment by endomorphosis** [comment] 2024-07-31 05:40
Okay, but i dont know what the design goals behind "resource management" are, e.g. autoscaling, s3 model storage, etc, its a vague term

**Comment by kevinintel** [comment] 2024-09-03 06:40
https://github.com/opea-project/GenAIInfra/issues/144 : autoscaling
V1.0 https://github.com/opea-project/GenAIInfra/issues/144
Q1/25: https://github.com/opea-project/GenAIEval/issues/58
Please sync with Kaajas, Samu

**Comment by kevinintel** [comment] 2024-09-05 09:06
https://github.com/opea-project/GenAIInfra/pull/386

**Closed** 2024-09-18 15:24 UTC
Labels: need more input
