### ISSUE TITLE
GMC failed to map the request to llm-service with endpoint v1/chat/completion

### ISSUE THREAD

**Issue by KfreeZ** [opea-project/GenAIInfra#130] opened 2024-06-25 06:54 UTC
When the request ```curl $accessUrl  -X POST  -d '{"language_from": "Golang","language_to": "Python","source_code": "package main\n\nimport \"fmt\"\nfunc main() {\n    fmt.Println(\"Hello, World!\");\n}"}' -H 'Content-Type: application/json'``` is sent to GMC router service, it is routed this request to llm-service/v1/chat/completion by GMC's router service.

But the output is not expected as below:

```
{"detail":[{"type":"missing","loc":["body","query"],"msg":"Field required","input":{"language_from":"Golang","language_to":"Python","source_code":"package main\n\nimport \"fmt\"\nfunc main() {\n    fmt.Println(\"Hello, World!\");\n}"}}]}
```

**Comment by KfreeZ** [comment] 2024-06-25 07:01
@zhlsunshine  @irisdingbj  please be noted this issue, we need to solve this 
cc @daisy-ycguo

**Comment by daisy-ycguo** [comment] 2024-06-27 13:10
codegen is also wrong
```
$ cat gmc_codegen.log
{"detail":[{"type":"missing","loc":["body","query"],"msg":"Field required","input":{"messages":"def print_hello_world():"}
```

**Comment by daisy-ycguo** [comment] 2024-07-05 02:02
GMC is by design to export the first service API. We just need to make sure the first service API is invocable and the output is reasonable. I think this is being fixed by this e2e test improvement PR https://github.com/opea-project/GenAIInfra/pull/142

So I think this issue can be closed.

**Closed by daisy-ycguo** 2024-07-05 02:02 UTC
